### ISSUE TITLE
Runner.GIF fails to convert and crashes the program

### ISSUE THREAD

**Issue by lurkio** [mungre/img2beeb#2]
[https://stardot.org.uk/forums/viewtopic.php?f=11&t=13294&p=262713#p262713](https://stardot.org.uk/forums/viewtopic.php?f=11&t=13294&p=262713#p262713)

**Comment by mungre** [comment]
MODE2 images are 160x256.  The GIFs are 640x512.  Each MODE2 pixel is represented by a patch of 2x4 pixels in a GIF.  This is just a sanity check that each of the 8 pixels in a patch is the same colour; that the GIF represents a naively scaled MODE2 image.

If you run

    dotnet run --configuration Release

this should do the conversion with the check disabled.  I'll convert the exception into a nicer warning later.

**Comment by lurkio** [comment]
> dotnet run --configuration Release

Tried that, and it said, "img2beeb: The animation requires more than 16 colours".

**Comment by mungre** [comment]
I was in a rush this morning and hadn't looked at the image.  It's had some filter applied to give that "glow" effect.  I've slightly improved the code that gets each pixel's colour: rather than using the top-left pixel in a 2x4 patch it takes the average.  However, this isn't enough to accurately recover the original pixel colours from this image.  And if the pixel colours are not interpreted accurately, the palette animation cannot be reconstructed.

Really, that image is beyond the scope of this project.  You would need to use some image processing tool (e.g. GIMP) to undo the effect of the filter and recover the original colours.  This project cannot feasibly do that - the range of possible filters that could have been applied is infinite.

**Comment by lurkio** [comment]
Fair enough.
